controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_acceleration_controller:
      type: forward_command_controller/ForwardCommandController

    forward_illegal1_controller:
      type: forward_command_controller/ForwardCommandController

    forward_illegal2_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

    # testing to see if the forward_position_controller gets the undeclared parameters
    gains:
      joint1:
        p: 1.0
        i: 2.0
        d: 3.0
    limits:
      joint1:
        has_position_limits: true
        x_min: 1.0
        x_max: 2.0
        
forward_velocity_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

    # testing to see if the forward_position_controller gets the undeclared parameters
    gains:
      joint1:
        p: 1.0
        i: 2.0
        d: 3.0
    limits:
      joint1:
        has_position_limits: true
        x_min: 1.0
        x_max: 2.0
        
forward_acceleration_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: acceleration

forward_illegal1_controller:
  ros__parameters:
    joints:
      - joint1
    interface_name: position

forward_illegal2_controller:
  ros__parameters:
    joints:
      - joint2
    interface_name: position
    
#testing to see if any nodes get the undeclared parameters
/**:
  ros__parameters:
    test_1:
      - test1
      - test2
    test_2: test
    test_gains:
      test_3:
        p: 1.0
        i: 2.0
        d: 3.0
    test_limits:
      test_4:
        has_position_limits: true
        x_min: 1.0
        x_max: 2.0
