controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position
    # testing to see if the forward_position_controller gets the undeclared parameters
    gains:
      joint1:
        p: 1.0
        i: 2.0
        d: 3.0
    limits:
      joint1:
        has_position_limits: true
        x_min: 1.0
        x_max: 2.0
        
#testing to see if any nodes get the undeclared parameters
/**:
  ros__parameters:
    test_1:
      - test1
      - test2
    test_2: test
    test_gains:
      test_3:
        p: 1.0
        i: 2.0
        d: 3.0
    test_limits:
      test_4:
        has_position_limits: true
        x_min: 1.0
        x_max: 2.0
